---
- name: Hello Ansible - quick start
  hosts: rpi
  become_user: root
  become: yes

  tasks:    
    - name: Update apt-get cache
      apt: >
        update_cache=yes
        cache_valid_time=3600
    
    - name: Update all packages to the latest version
      apt: > 
        upgrade=yes
    - name: Update repositories cache and install "php5-common" package
      apt: 
        name: lightdm
        
    - name: Copy file LCD-show.tar.gz
      copy:
        src: ./LCD-show.tar.gz
        dest: /home/pi/LCD-show.tar.gz
        owner: pi
        group: pi
        mode: 0644
    
    - name: untar
      unarchive:
        src: ./LCD-show.tar.gz
        creates: /home/pi/LCD-show/LCD35-show
        dest: /home/pi

    - name: activate
      shell: ./LCD35-show
      args:
        chdir: /home/pi/LCD-show/
        creates: /etc/X11/xorg.conf.d
