---
- name: Hello Ansible - quick start
  hosts: rpi
  become_user: pi
  become: yes
      
  tasks:    
    - name: Update apt-get cache
      apt: >
        update_cache=yes
        cache_valid_time=3600
      become_user: root
      become: yes   
 
    - name: Update all packages to the latest version
      apt: > 
        upgrade=yes      
      become_user: root
      become: yes


    - name: Copy file LCD-show.tar.gz
      copy:
        src: ./LCD-show.tar.gz
        dest: /home/pi/LCD-show.tar.gz
    
    - name: untar
      unarchive:
        src: ./LCD-show.tar.gz
        creates: /home/pi/LCD-show/LCD35-show
        dest: /home/pi

    - name: activate
      shell: ./LCD35-show
      args:
        chdir: /home/pi/LCD-show/
        creates: /etc/X11/xorg.conf.d

    - name: Install "xserver-xorg-video-fbdev" package 
      apt: 
        name: xserver-xorg-video-fbdev
       
    - name: Copy file 99-fbdev.conf
      copy:
        src: ./99-fbdev.conf
        dest: /usr/share/X11/xorg.conf.d/99-fbdev.conf
      become_user: root
      become: yes

    - name: Copy file autostart
      copy:
        src: ./autostart
        dest: /etc/xdg/lxsession/LXDE/autostart 
      become_user: root
      become: yes

    - name: set Display
      lineinfile:
        dest: /home/pi/.bashrc
        line: 'export DISPLAY=:0.0'
